Repository Aryan-Chharia/Computer-Vision-Projects, pull requests merged in 2024-10, with the labels that each got.

#23 Pose detection using opencv and mediapipe.
  pose detection/landmarks.csv
  pose detection/pose detection.ipynb
  pose detection/requirements.txt
Labels: gssoc-ext, hacktoberfest-accepted, level1

#37 Detection through OpenCV functions
  Detection through OpenCV functions/Results/blured image output.png
  Detection through OpenCV functions/Results/color detection output.png
  Detection through OpenCV functions/Results/edge detection output.png
  Detection through OpenCV functions/Results/original.jpg
  Detection through OpenCV functions/Results/shape detection output.png
  Detection through OpenCV functions/Results/sharpened image output.png
  Detection through OpenCV functions/main.py
Labels: gssoc-ext, hacktoberfest-accepted, level1

#40 Added requirement file
  requirements.txt
Labels: gssoc-ext, hacktoberfest-accepted, level1

#65 Added Document Scanner
  Document Scanner/README.md
  Document Scanner/__pycache__/ocr.cpython-312.pyc
  Document Scanner/__pycache__/scanner.cpython-312.pyc
  Document Scanner/__pycache__/utils.cpython-312.pyc
  Document Scanner/main.py
  Document Scanner/ocr.py
  Document Scanner/requirements.txt
  Document Scanner/scanner.py
  Document Scanner/utils.py
Labels: gssoc-ext, hacktoberfest-accepted, level1

#67 Eye Disease Detection
  Eye Diseases Detection/Images/Model Eval.png
  Eye Diseases Detection/Images/cataract.png
  Eye Diseases Detection/Images/countplot.png
  Eye Diseases Detection/Images/diabetic_retionpathy.png
  Eye Diseases Detection/Images/eye disease acc.png
  Eye Diseases Detection/Images/glucoma.png
  Eye Diseases Detection/Images/model.png
  Eye Diseases Detection/Images/normal.png
  Eye Diseases Detection/Images/true& predict eye disease.jpg
  Eye Diseases Detection/Model/Models/Eye_Diseases_Classification.ipynb
  Eye Diseases Detection/README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#69 added CONTRIBUTING.md
  CONTRIBUTING.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#72 Optimized YOLO Object Detection in main.py
  Object detection/main.py
Labels: gssoc-ext, hacktoberfest-accepted, level1

#78 Update README.md
  README.md
Labels: enhancement

#76 Added fire detection using YOLOv8 implementation for beginners
  Fire-Detection-YOLOv8/README.md
  Fire-Detection-YOLOv8/main.py
Labels: gssoc-ext, hacktoberfest-accepted, level1

#80 added face recognition project
  smart_attendance_system/.gitignore
  smart_attendance_system/README.md
  smart_attendance_system/dlib-19.24.99-cp312-cp312-win_amd64.whl
  smart_attendance_system/face_rec.py
  smart_attendance_system/photos/Anirudh.jpg
  smart_attendance_system/photos/Ashaya.jpg
  smart_attendance_system/photos/Benak.jpg
  smart_attendance_system/photos/Biden.jpeg
  smart_attendance_system/photos/Harsha.jpg
  smart_attendance_system/photos/Jobs.jpeg
  smart_attendance_system/photos/Obama.jpg
  smart_attendance_system/photos/Tata.jpg
  smart_attendance_system/photos/Tesla.jpeg
  smart_attendance_system/requirements.txt
  smart_attendance_system/results/Screenshot 2024-10-06 193552.png
  smart_attendance_system/results/Screenshot 2024-10-06 193656.png
  smart_attendance_system/results/Screenshot 2024-10-06 193721.png
  smart_attendance_system/smart_attendance.py
Labels: gssoc-ext, hacktoberfest-accepted, level1

#87 Added the Quiz Master Project (#47 Issue)
  QuizMaster/Images/1.jpg
  QuizMaster/Images/2.jpg
  QuizMaster/Images/3.jpg
  QuizMaster/Images/4.jpg
  QuizMaster/Images/5.jpg
  QuizMaster/Readme.md
  QuizMaster/cam.py
Labels: gssoc-ext, hacktoberfest-accepted, level1

#88 Blood Cell Cancer Classification using CNN and EfficientNetB3
  Blood Cell Cancer Detection using CNN and EfficientNetB3/ReadMe.md
  Blood Cell Cancer Detection using CNN and EfficientNetB3/blood-cell-cancer-using-cnn-and-efficientnetb3.ipynb
Labels: gssoc-ext, hacktoberfest-accepted, level2

#92 Updated README.md
  README.md
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level1

#103 Volume Control Using Hand Gestures
  .idea/.gitignore
  .idea/Computer-Vision-Projects.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  Gesture Volume/GestureVolume.py
  Gesture Volume/HandTrackingModule.py
  Gesture Volume/README.md
  Gesture Volume/docs/Untitledvideo-MadewithClipchamp2-ezgif.com-video-to-gif-converter.gif
  Gesture Volume/docs/docs.md
  Gesture Volume/requirements.txt
Labels: gssoc-ext, hacktoberfest-accepted, level1

#108 Image File Format Converter Using OpenCV
  Format Converter/Readme.md
  Format Converter/main.py
  Format Converter/method.html
  Format Converter/static/pract4.jpg
  Format Converter/static/pract4.png
  Format Converter/templates/about.html
  Format Converter/templates/contact.html
  Format Converter/templates/help.html
  Format Converter/templates/index.html
  Format Converter/uploads/pract4.png
  requirements.txt
Labels: gssoc-ext, hacktoberfest-accepted, level2

#121 ECG Report Classification Using Computer Vision
  ECG_Report_Analyzer/Model.ipynb
  ECG_Report_Analyzer/README.md
  ECG_Report_Analyzer/requirements.txt
Labels: gssoc-ext, hacktoberfest-accepted, level2

#124 Lenses Detector Using OpenCV
  Lenses detector/Readme.md
  Lenses detector/main.py
  Lenses detector/method.html
  Lenses detector/results.html
  results.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#125 Waste Classification Using Keras And OpenCV
  Waste Classification/Readme.md
  Waste Classification/Resources/Bins/1.png
  Waste Classification/Resources/Bins/2.png
  Waste Classification/Resources/Bins/3.png
  Waste Classification/Resources/Bins/4.png
  Waste Classification/Resources/Model/keras_model.h5
  Waste Classification/Resources/Model/labels.txt
  Waste Classification/Resources/Waste/1.png
  Waste Classification/Resources/Waste/2.png
  Waste Classification/Resources/Waste/3.png
  Waste Classification/Resources/Waste/4.png
  Waste Classification/Resources/Waste/5.png
  Waste Classification/Resources/Waste/6.png
  Waste Classification/Resources/Waste/7.png
  Waste Classification/Resources/Waste/8.png
  Waste Classification/Resources/arrow.png
  Waste Classification/Resources/bgimg.png
  Waste Classification/main.py
  Waste Classification/method.html
  Waste Classification/result.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#153 Added style transfer application
  Style-Transfer/README.md
  Style-Transfer/dataset/c1.jpg
  Style-Transfer/dataset/s1.jpg
  Style-Transfer/main.py
Labels: gssoc-ext, hacktoberfest-accepted, level1

#175 Added diabetes prediction
  Diabetes-Prediction/README.md
  Diabetes-Prediction/diabetes.csv
  Diabetes-Prediction/diabetes.ipynb
  Diabetes-Prediction/images/1.PNG
  Diabetes-Prediction/images/2.PNG
  Diabetes-Prediction/images/3.PNG
  Diabetes-Prediction/images/4.PNG
Labels: gssoc-ext, hacktoberfest-accepted, level2

#187 Leukaemia classification
  Leukaemia Classification/README.md
  Leukaemia Classification/cancer.PNG
  Leukaemia Classification/dataset
  Leukaemia Classification/image-19.png
  Leukaemia Classification/model-code.ipynb
  Leukaemia Classification/test-code.ipynb
  Leukaemia Classification/weights.hdf5
Labels: gssoc-ext, hacktoberfest-accepted, level1

#188 Anomaly detection with mask
  Anomaly Detection in Industrial Inspection/README.md
  Anomaly Detection in Industrial Inspection/Results/Screenshot 2024-10-13 180925.png
  Anomaly Detection in Industrial Inspection/Results/Screenshot 2024-10-13 180947.png
  Anomaly Detection in Industrial Inspection/anomalyprediction-with-mask.ipynb
Labels: gssoc-ext, hacktoberfest-accepted, level1

#177 Find Coordinates
  Find Coordinates/Images/Input.jpg
  Find Coordinates/Images/Output.png
  Find Coordinates/Readme.md
  Find Coordinates/main.py
Labels: gssoc-ext, hacktoberfest-accepted, level1

#184 Implement Stone Paper Scissor Game Using Hand tracing with OpenCV
  Rock-Paper-Scissor-Game/1.png
  Rock-Paper-Scissor-Game/2.png
  Rock-Paper-Scissor-Game/3.png
  Rock-Paper-Scissor-Game/BG.png
  Rock-Paper-Scissor-Game/main.py
  Rock-Paper-Scissor-Game/readme.md
  Rock-Paper-Scissor-Game/requirements.txt
  Rock-Paper-Scissor-Game/rock-paper-scissor.mp4
Labels: gssoc-ext, hacktoberfest-accepted, level1

#180 Added Posture Monitoring: Detecting Neck Angle to Warn About Mobile Usage Health Risks
  Real-Time Neck Posture Analysis with Health Alerts/Output.png
  Real-Time Neck Posture Analysis with Health Alerts/Readme.md
  Real-Time Neck Posture Analysis with Health Alerts/neck_posture_monitoring.py
Labels: gssoc-ext, hacktoberfest-accepted, level1

#200 Signature Verification System Using OpenCV
  Signature Verification System/Readme.md
  Signature Verification System/app.py
  Signature Verification System/methods.html
  Signature Verification System/results/Screenshot 2024-10-13 001054.png
  Signature Verification System/results/Screenshot 2024-10-13 001842.png
  Signature Verification System/results/Screenshot 2024-10-13 001923.png
  Signature Verification System/templates/index.html
  Signature Verification System/uploads/my sign_page-0001-min.jpg
  Signature Verification System/uploads/my sign_page-0001.jpg
Labels: gssoc-ext, hacktoberfest-accepted, level1

#210 Weapon Detection System
  WEAPON-DETECTION-SYSTEM/.gitattributes
  WEAPON-DETECTION-SYSTEM/README.md
  WEAPON-DETECTION-SYSTEM/req.txt
  WEAPON-DETECTION-SYSTEM/weapon_detection.py
  WEAPON-DETECTION-SYSTEM/weapon_detection1.py
  WEAPON-DETECTION-SYSTEM/yolov3_testing.cfg
Labels: gssoc-ext, hacktoberfest-accepted, level1

#204 Generate ML model data through video
  Generate ML model with video/main.ipynb
  Generate ML model with video/readme.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#222 #220 Added AI 3D Object Reconstruction Python Script
  Ai 3d Construction/3d_construction.py
  Ai 3d Construction/README.md
  Ai 3d Construction/Screenshot 2024-10-17 213410.png
  Ai 3d Construction/left_image.jpg
  Ai 3d Construction/right_image.jpg
Labels: gssoc-ext, hacktoberfest-accepted, level1

#236 Created README file for "Object Detection" Project
  Object detection/README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#255 Denoise net an auto encoder for image classification and creating a model for effectively noising and denoising images
  Auto-Encoder for Noising and Denoising Images/Denoising_and_Noising_images (1).ipynb
  Auto-Encoder for Noising and Denoising Images/README.md
  Auto-Encoder for Noising and Denoising Images/env.txt
  Auto-Encoder for Noising and Denoising Images/gitignore.txt
  Auto-Encoder for Noising and Denoising Images/requirements.txt
  Auto-Encoder for Noising and Denoising Images/source files
Labels: gssoc-ext, hacktoberfest-accepted, level1

#254 Eye-Controlled Mouse using Eye Tracking
  Mouse Control using Eye Tracking/main.py
  Mouse Control using Eye Tracking/readme.md
  Mouse Control using Eye Tracking/requirements.txt
Labels: gssoc-ext, hacktoberfest-accepted, level1

#258 Done the enhancements and also added some new sections
  CONTRIBUTING.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#261 ADD RATIOS IN THE DISPARITY MAP FOR MNORE PRECISE CONSTRUCTIONS
  Mouse Control using Eye Tracking/main.py
Labels: gssoc-ext, hacktoberfest-accepted, level1

#264 Added Image segmentations in real time
  Image Segment in real time/input image.png
  Image Segment in real time/main.ipynb
  Image Segment in real time/output.png
  Image Segment in real time/readme.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#278 Added multimodal vqa using blip & clip models
  Multimodal VQA using BLIP & CLIP/Multimodal VQA files
  Multimodal VQA using BLIP & CLIP/Mutimodal VQA.(using CLIP and VizWiz dataset).ipynb
  Multimodal VQA using BLIP & CLIP/README.md
  Multimodal VQA using BLIP & CLIP/VQA Model using BLIP.txt
  Multimodal VQA using BLIP & CLIP/VQA_image_processing(Using_BLIP) (1).ipynb
  Multimodal VQA using BLIP & CLIP/requirements (2).txt
  Multimodal VQA using BLIP & CLIP/src/src_files
  Multimodal VQA using BLIP & CLIP/src/test_img2 (1).png
  Multimodal VQA using BLIP & CLIP/src/test_img3 (1).png
  Multimodal VQA using BLIP & CLIP/src/test_img4 (1).png
  Multimodal VQA using BLIP & CLIP/src/test_img_ronaldo (1).jpg
Labels: gssoc-ext, hacktoberfest-accepted, level1

#290 Added Self Driving Car Project | Issue #266
  Self  Driving Car/README.md
  Self  Driving Car/findingLanes.py
  Self  Driving Car/images/averageSmoothLines.png
  Self  Driving Car/images/cannyEdgeDetection.png
  Self  Driving Car/images/findingLanes.png
  Self  Driving Car/images/regionOfInterest.png
  Self  Driving Car/images/test_image.jpg
Labels: gssoc-ext, hacktoberfest-accepted, level1

#289 Add LipNet | Issue #240
  LipNet/LipNet.ipynb
  LipNet/README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#285 Added Sketch Effect Project
  Real_Time_Sketch_Effect/README.md
  Real_Time_Sketch_Effect/sketch_effect.py
Labels: gssoc-ext, hacktoberfest-accepted, level1

#270 Traffic sign detection
  Traffic Sign Detection/README.md
  Traffic Sign Detection/requirements.txt
  Traffic Sign Detection/trafffic_sign_detection.ipynb
  Traffic Sign Detection/traffic_sign_detection.py
Labels: gssoc-ext, hacktoberfest-accepted, level1

#75 Cloth Classifier
  Clothing Classifier/main.ipynb
Labels: gssoc-ext, hacktoberfest-accepted, level1

#127 AI Calculator Using Computer Vision and GenAI
  Virtual Calculator/Readme.md
  Virtual Calculator/app.py
Labels: gssoc-ext, hacktoberfest-accepted, level2

#286 "Road Condition Monitoring" Project added
  Road Condition Monitoring/README.md
  Road Condition Monitoring/Results.pdf
  Road Condition Monitoring/data_preprocessing.py
  Road Condition Monitoring/evaluate_model.py
  Road Condition Monitoring/inference.py
  Road Condition Monitoring/requirements.txt
  Road Condition Monitoring/road_condition_monitor.ipynb
  Road Condition Monitoring/train_model.py
Labels: gssoc-ext, hacktoberfest-accepted, level1

#297 added image-to-3D model
  image-to-3D model/model.py
  image-to-3D model/model_readme.md
  image-to-3D model/requirements.txt
Labels: gssoc-ext, hacktoberfest-accepted, level1
