Repository Aryan-Chharia/Computer-Vision-Projects, pull requests merged in 2024-11, with the labels that each got.

#319 updated README
  Images_Read_Me/SSD_model.jpeg
  Images_Read_Me/YOLO.png
  README.md
Labels: documentation, gssoc-ext, hacktoberfest-accepted, level1

#318 Gesture volume Control
  Gesture Volume/Gesture-Volume.py
  Gesture Volume/GestureVolume.py
  Gesture Volume/HandTrackingModule.py
  Gesture Volume/README.md
  Gesture Volume/docs/Untitledvideo-MadewithClipchamp2-ezgif.com-video-to-gif-converter.gif
  Gesture Volume/docs/docs.md
  Gesture Volume/docs/recording.mkv
  Gesture Volume/requirements.txt
  Gesture Volume/test_Gest-vol.py
Labels: gssoc-ext, hacktoberfest-accepted, level1

#327 Create README.md
  Object Size Detection/README.md
  Object Size Detection/Results/res1.png
  Object Size Detection/Results/res2.png
  Object Size Detection/Results/res3.png
  Object Size Detection/app.py
  Object Size Detection/requirements.txt
  Object Size Detection/res1.png
  Object Size Detection/res2.png
  Object Size Detection/res3.png
Labels: gssoc-ext, hacktoberfest-accepted, level1

#334 Gesture-Based Keyboard Interface Using Webcam #332
  Gesture-Based Keyboard Interface Using Webcam/README.md
  Gesture-Based Keyboard Interface Using Webcam/main.py
  Gesture-Based Keyboard Interface Using Webcam/output/Screenshot 2024-11-06 164915.png
  Gesture-Based Keyboard Interface Using Webcam/output/desktop.ini
  Gesture-Based Keyboard Interface Using Webcam/output/typed_text_20241106_160434.txt
  Gesture-Based Keyboard Interface Using Webcam/requirements.txt
Labels: gssoc-ext, hacktoberfest-accepted, level1

#335 CLIP Image Classification
  CLIP Image Classification/CLIP_Image_Classification.py
  CLIP Image Classification/Readme.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#336 Real time object measurement by opencv #34
   Real Time Oject Measurement/1.jpeg
   Real Time Oject Measurement/ObjMeasurement.py
   Real Time Oject Measurement/README.md
   Real Time Oject Measurement/utils.py
Labels: gssoc-ext, hacktoberfest-accepted, level2

#330 Added AI-Powered Super-Resolution and Image Restoration for Historical Photos model
  AI Super-Resolution and Image Restoration/Denoise_tiger.jpg
  AI Super-Resolution and Image Restoration/Noise_tiger.jpg
  AI Super-Resolution and Image Restoration/README.md
  AI Super-Resolution and Image Restoration/main.py
Labels: gssoc-ext, hacktoberfest-accepted, level1

#326 added digital white-board-reader
  Digital-whiteboard-reader-model/Readme.md
  Digital-whiteboard-reader-model/main.py
Labels: gssoc-ext, hacktoberfest-accepted, level1

#339 added back-to-top scroll up in readme
  README.md
Labels: documentation, gssoc-ext, hacktoberfest-accepted, level1

#341 Add Defective Captcha Image Recognition #9
  Defective Captcha Image Recognition/captcha_solve.py
  Defective Captcha Image Recognition/images/12jyj42.png
  Defective Captcha Image Recognition/images/CaptchaImage.png
  Defective Captcha Image Recognition/ocr_notebook.ipynb
  Defective Captcha Image Recognition/readme.md
  Defective Captcha Image Recognition/result/Screenshot 2024-11-10 133703.png
  Defective Captcha Image Recognition/result/result.pdf
Labels: gssoc-ext, hacktoberfest-accepted, level2
